## static PV is created by k8s admin
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain ##retain means does not delete the data , delete when pod is deleted the delete the data , recyle means keep the data after pd delet
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-05c44c7e2844068a4
