apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-dynamic-storage"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
   project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: efs-dynamic
        mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-dynamic
      persistentVolumeClaim:
        claimName: efs-claim-dynamic
