apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
   project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-static
      mountPath: /usr/share/nginx/html


      
  volumes:
  - name: efs-static
    persistentVolumeClaim:
      claimName: efs-claim

  nodeSelector:
    topology.ebs.csi.aws.com/zone: us-east-1b

---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 type: LoadBalancer
 selector:
   project: roboshop

 ports:
   - protocol: TCP
     port: 80
     targetPort: 80 ##This is container port

      