apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
   project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-static-storage
      mountPath: /usr/share/nginx/html


      
  volumes:
  - name: persistent-static-storage
    persistentVolumeClaim:
      claimName: ebs-claim

  nodeSelector:
    topology.ebs.csi.aws.com/zone: us-east-1b

---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 type: LoadBalancer
 selector:
   project: roboshop

 ports:
   - protocol: TCP
     port: 80
     targetPort: 80 ##This is container port

      