apiVersion: v1
kind: Pod
metadata: 
 name: multicontianers
 labels: 
  env: dev
  project: roboshop
spec: 
  containers:
  - name: nginx
    image: nginx
  - name: alamlinux
    image: almalinux:9
    command: ["sleep", "1000"]