apiVersion: v1
kind: Pod
metadata: 
 name: nginx-service-pod
labels:
 name: frontend-nginx
 project: roboshop
 component: frontend
 environment: dev
spec:
  containers:
   - name: nginx
     image: nginx