apiVersion: v1
kind: ReplicaSet
metadata:
##this is for the replicaset
 name: replica-set
 labels: 
  name: replica-set
  project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  ##pod configuration
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
       - name: nginx
         image: nginx