apiVersion: apps/v1
kind: ReplicaSet
metadata:
##this is for the replicaset
 name: replica-set
 labels: 
  name: replica-set
  project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  ##pod configuration
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
       - name: nginx
         image: nginx