apiVersion: v1
kind: Pod
metadata:
 name: resource-utlization
spec: 
  containers:
   - name: resources-ngix
     image: nginx
     resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"