apiVersion: v1
kind: Service
metadata:
 name: nginx-service-np
spec:
 type: NodePort
   
 selector:
   project: roboshop
   component: frontend
   environment: dev
   purpose: nodeport-creation
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80 ##This is container port